### ISSUE TITLE
Что за параметры ? \CIBlockParameters::GetIBlockTypes(Array("-" => " "))

### ISSUE THREAD

**Issue by ghost** [maraduda/bx-components#1]
Подскажите что за параметры Array("-" => " ") вы передали?

**Comment by maraduda** [comment]
Это первый элемент результирующего массива
http://bxapi.ru/src/?module_id=iblock&name=CIBlockParameters::GetIBlockTypes

**Comment by dermanov-ru** [comment]
Да, кстати, зачем он нужен-то?

> Вторник, 16 февраля 2016, 6:26 -08:00 от Andrey Maraduda notifications@github.com:
> 
> Это первый элемент результирующего массива
> http://bxapi.ru/src/?module_id=iblock&name=CIBlockParameters::GetIBlockTypes
> —
> Reply to this email directly or  view it on GitHub .

---

С уважением,
Марк Дерманов
моб: +7 (921) 769-56-55

**Comment by ghost** [comment]
Разобрался. Это нужно для того что бы в админке в визуальных настройках компонента по умолчанию было выбрано пустое значение в селекте "тип инфоблока".

**Comment by dermanov-ru** [comment]
А, все разобрался. Сначала не понял, что это за файл.
Это чтобы можно было сбросить тип иблока (и также для иблоков) при настройке через виз редактор.
Только немного странная логика у метода. 
Можно было бы вставить в начало полученного массива, фиктивный элемент для сброса значения, например с текстом "- Выбрать значение -".
Было бы сразу понятно)
